# Generated by Django 4.1.2 on 2022-10-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarRentalApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="customer_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="rental_status",
            field=models.BooleanField(default=False),
        ),
    ]
